KAFKA_BOOTSTRAP_SERVERS = "localhost:9092"

TOPIC_FLIGHT_DATA = "flight-data"
TOPIC_WEATHER_DATA = "weather-data"

MYSQL_HOST = "localhost"
MYSQL_PORT = 3307
MYSQL_USER = "YOUR_USERNAME"
MYSQL_PASSWORD = "YOUR_PASSWORD"
MYSQL_DB = "flights"

OPENWEATHER_API_KEY = "YOUR_API_KEY"
OPENSKY_USERNAME = "YOUR_USERNAME"
OPENSKY_PASSWORD = "YOUR_PASSWORD"

TOPIC_TELEMETRY = "telemetry-data"

AVIATIONSTACK_API_KEY = "YOUR_API_KEY"
TOPIC_METADATA = "metadata-data"

AIRLABS_API_KEY = "YOUR_API_KEY"
TOPIC_AIRPORT = "airport-data"
